let body = document.querySelector('body');
let main = document.createElement('main');
let script = document.querySelector('script');
body.insertBefore(main, script);
let container = document.createElement('div');
container.setAttribute('class', 'container');
main.appendChild(container);
let h1 = document.createElement('h1');
h1.innerText = 'WHAT PEOPLE SAY';
container.appendChild(h1);
let h2 = document.createElement('h2');
container.appendChild(h2);
h2.innerText = 'Reviews';
// 
let testiItems = document.createElement('div');
testiItems.setAttribute('class', 'testimonials-item');
container.appendChild(testiItems);
let item = document.createElement('div');
testiItems.appendChild(item);
let item2 = document.createElement('div');
testiItems.appendChild(item2);
let item3 = document.createElement('div');
testiItems.appendChild(item3);
item.setAttribute('class', 'item');
item2.setAttribute('class', 'item');
item3.setAttribute('class', 'item');
let p = document.createElement('p');
let p2 = document.createElement('p');
let p3 = document.createElement('p');
item.appendChild(p);
item2.appendChild(p2);
item3.appendChild(p3);
p.innerText = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo soluta quos itaque laborum necessitatibus rem? Dignissimos excepturi a, repudiandae labore sapiente libero ducimus quis nesciunt, similique totam eligendi harum quasi.';
p2.innerText = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo soluta quos itaque laborum necessitatibus rem? Dignissimos excepturi a, repudiandae labore sapiente libero ducimus quis nesciunt, similique totam eligendi harum quasi.';
p3.innerText = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo soluta quos itaque laborum necessitatibus rem? Dignissimos excepturi a, repudiandae labore sapiente libero ducimus quis nesciunt, similique totam eligendi harum quasi.';
let img = document.createElement('img');
let img2 = document.createElement('img');
let img3 = document.createElement('img');
item.appendChild(img);
item2.appendChild(img2);
item3.appendChild(img3);
img.setAttribute('src', 'https://cdn.pixabay.com/photo/2018/03/06/22/57/portrait-3204843_960_720.jpg');
img2.setAttribute('src', 'https://cdn.pixabay.com/photo/2016/06/06/17/05/model-1439909_960_720.jpg');
img3.setAttribute('src', 'https://cdn.pixabay.com/photo/2016/11/29/09/38/adult-1868750_960_720.jpg');
let h4 = document.createElement('h4');
let h4_2 = document.createElement('h4');
let h4_3 = document.createElement('h4');
item.appendChild(h4);
item2.appendChild(h4_2);
item3.appendChild(h4_3);
h4.innerText = 'John Doe';
h4_2.innerText = 'Pete Jones';
h4_3.innerText = 'Mark Wilson';